openapi: 3.1.0
info:
  title: Consulta de Precios - OpenAPI 3.0
  description: |-
    API para consulta de precios
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Prices
    description: Consultas de precios de artículos
paths:
  /v1/prices:
    get:
      tags:
        - Prices
      summary: Busca un artículo por marca, id prod. y fecha/hora
      description: Permite buscar un artículo indicando el código de marca, el id de artículo y la fecha/hora de consulta
      #operationId: v1PricesGet
      parameters:
        - $ref: "#/components/parameters/brandId"
        - $ref: "#/components/parameters/productId"
        - $ref: "#/components/parameters/applicationDatetime"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceApiResponse"
        '400':
          description: Invalid BrandId/ProductId/Datetime value
          content:
            application/json:
              schema: {}
        '404':
          description: BrandId/ProductId/Datetime not found
          content:
            application/json:
              schema: {}
        '500':
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    PriceApiResponse:
      type: object
      properties:
        brand_id:
          type: integer
          format: int32
          example: "1"
          minimum: 0
        product_id:
          type: integer
          format: int32
          example: "35455"
          minimum: 0
        start_date:
          type: string
          format: date-time
          example: "2020-06-14T00:00:00"
        end_date:
          type: string
          format: date-time
          example: "2020-12-31T23:59:59"
        price:
          type: number
          format: decimal
          example: "35.50"
          minimum: 0
        price_list:
          type: integer
          format: int32
          example: "1"
          minimum: 0
        curr:
          type: string
          example: "EUR"
          minLength: 3
          maxLength: 3
  parameters:
    brandId:
      name: brand_id
      in: query
      description: Id de la marca
      required: true
      style: form
      schema:
        type: integer
        format: int32
        minimum: 0
        example: "1"
    productId:
      name: product_id
      in: query
      description: Id del producto
      required: true
      style: form
      schema:
        type: integer
        format: int32
        minimum: 0
        example: "35455"
    applicationDatetime:
      name: application_datetime
      in: query
      description: Fecha/hora de consulta
      required: true
      style: form
      schema:
        type: string
        format: date-time
        example: "2020-06-14 00:00:00"
  responses:
    InternalServerError:
      description: |
        An error occured while processing the request.
        Please, contact admin@business.com
      content:
        application/json:
          schema: {}

